# Lab 2: Q2 - Implementing exit() system call
# Makefile for test_exit

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=exit_test
SRCS=exit_test.c
BINDIR=/testbin

.include "$(TOP)/mk/os161.prog.mk"
